{% set name = "ada-cpp" %}
{% set version = "0.1.1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: https://github.com/Krande/adacpp/archive/refs/tags/v{{ version }}.tar.gz
    sha256: 719409e9f2b7d9e0eb778522c954e8c48a052db8f3ffb6a59b0c4684d8efe7db
    patches:
      - patches/remove_hardcoded_osx_sysroot_and_deployment_target.patch

build:
  skip: true  # [py<310]
  number: 0
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - "{{ compiler('c') }}"
    - "{{ compiler('cxx') }}"
    - "{{ cdt('mesa-libGL-devel') }}"  # [unix] provides OpenGL development libraries
    - cmake
    - ninja  # [win]
    - make  # [unix]

  host:
    - python
    - occt
    - ifcopenshell
    - cgal-cpp
    - scikit-build-core
    - nanobind
    - cli11
    - tinygltf
    - gmsh
    - pip

  run:
    - python
    - "{{ pin_compatible('gmsh', max_pin='x.x') }}"

test:
  source_files:
    - tests
    - files
  requires:
    - pytest
  commands:
    - pytest tests

about:
  home: https://github.com/Krande/adacpp
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A module with drop-in replacement functions for ada-py written in c++ to improve performance."

extra:
  recipe-maintainers:
    - Krande
