{% set name = "ada-cpp" %}
{% set version = "0.2.0" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  - url: https://github.com/Krande/adacpp/archive/refs/tags/v{{ version }}.tar.gz
    sha256: fadfd136b408ede0abab414aec056c353ae36e51aa063e09d2eb88ce9f0e2fd8

build:
  skip: true  # [py<310]
  number: 1
  run_exports:
    - {{ pin_subpackage(name, max_pin='x.x.x') }}

requirements:
  build:
    - {{ stdlib("c") }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ cdt('mesa-libGL-devel') }}  # [unix] provides OpenGL development libraries
    - cmake
    - ninja  # [win]
    - make  # [unix]

  host:
    - python
    - occt
    - ifcopenshell
    - cgal-cpp
    - scikit-build-core
    - nanobind
    - cli11
    - tinygltf
    - gmsh
    - pip

  run:
    - python
    - {{ pin_compatible('gmsh', max_pin='x.x') }}

test:
  source_files:
    - tests
    - files
  requires:
    - pytest
    - ada-py
  commands:
    - pytest tests

about:
  home: https://github.com/Krande/adacpp
  license: "GPL-3.0-or-later"
  license_family: GPL3
  license_file: LICENSE
  summary: "A module with drop-in replacement functions for ada-py written in c++ to improve performance."

extra:
  recipe-maintainers:
    - Krande
